var questions = [{
    "question": "My grandparents walk _____ twenty minutes a day.",
    "option1": "for",
    "option2": "since",
    "option3": "to",
    "option4": "about",
    "answer": 1
},
{
    "question": "The man was ____ smuggling and murder.",
    "option1": "admit to",
    "option2": "afraid of",
    "option3": "accuse of",
    "option4": "agree with",
    "answer": 3
},
{
    "question": "Tollywood movies can be ______ Hollywood in some respects.",
    "option1": "Compare to",
    "option2": "Compare with",
    "option3": "Commit to",
    "option4": "Combine into",
    "answer": 2 },
{
    "question": "Indian Institute of Technology is _________ AICTE.",
    "option1": "Affiliated with",
    "option2": "Affiliated to",
    "option3": "Admit of",
    "option4": "Admit for",
    "answer": 2},
{
    "question": "A business man  is _________  the Bank manager for a Loan.",
    "option1": "Agree to",
    "option2": "Apologize for",
    "option3": "Appeal to",
    "option4": "Appeal to be",
    "answer":3 },
{
    "question": "She ___________ his rude behaviour.",
    "option1": "Complain against",
    "option2": "Complain of",
    "option3": "Complain for",
    "option4": "Complain on",
    "answer": 2},
{
    "question": "______ the better team, we lost the match.",
    "option1": "Despite of being",
    "option2": "Despite",
    "option3": "Despite being",
    "option4": "Although",
    "answer":3 }, {
    "question": "By this time next year, I ______ all my exams.",
    "option1": "will have taken",
    "option2": "will take",
    "option3": "take",
    "option4": "have taken",
    "answer":1 }, {
    "question": "She looks ______ she's going to be sick.",
    "option1": "as if",
    "option2": "as",
    "option3": "likes",
    "option4": "if",
    "answer": 1}, {
    "question": "We would never have had the accident if you ______ so fast.",
    "option1": "wouldn't been driving",
    "option2": "hadn't been driving",
    "option3": "had driven",
    "option4": "wouldn't drive",
    "answer": 2}, {
    "question": "Would you mind ______ the window?",
    "option1": "closing",
    "option2": "close",
    "option3": "to close",
    "option4": "closed",
    "answer":1 }, {
    "question": "The doctor gave me a ______ for some medicine yesterday.",
    "option1": "note",
    "option2": "receipt",
    "option3": "prescription",
    "option4": "recipe",
    "answer": 3}, {
    "question": "You aren't allowed to use your mobile so ______.",
    "option1": "it's no point to leave it on",
    "option2": "it's no point in leaving it on",
    "option3": "there's no point in leaving it on",
    "option4": "there's no point to leave it on",
    "answer":3 }, {
    "question": "The best way to learn a language is ______ a little every day.",
    "option1": "speak",
    "option2": "in speaking",
    "option3": "to speaking",
    "option4": "by speaking",
    "answer": 4}, {
    "question": "Can you tell me when ______ ?",
    "option1": "the train leaves",
    "option2": "does the train leave",
    "option3": "leaves the train",
    "option4": "does leave the train",
    "answer":1 }, {
    "question": "We arrived ______ England two days ago.",
    "option1": "to",
    "option2": "in",
    "option3": "on",
    "option4": "at",
    "answer": 2}, {
        "question": "You ______ the cleaning. I would have done it tonight.",
    "option1": "needn't have done",
    "option2": "couldn't have done",
    "option3": "can't have done",
    "option4": "wouldn't have done",
    "answer":1 }, {
    "question": "The tree ______ by lightning.",
    "option1": "was flashed",
    "option2": "struck",
    "option3": "was struck",
    "option4": "flashed",
    "answer": 3}, {
    "question": "______ to school yesterday?",
    "option1": "Do you walk",
    "option2": "Did you walked",
    "option3": "Did you walk",
    "option4": "Have you walked",
    "answer": 3}, {
    "question": "He told me that he ______ in Spain the previous year.",
    "option1": "has been working",
    "option2": "had been working",
    "option3": "has worked",
    "option4": "had been worked",
    "answer":2 }, {
    "question": "I ______ a reply to my letter in the next few days.",
    "option1": "hope",
    "option2": "except",
    "option3": "wait for",
    "option4": "get",
    "answer": 2}, {
        "question": "They have put speed bumps on the road to ______ accidents.",
    "option1": "avoid",
    "option2": "prohibit",
    "option3": "prevent",
    "option4": "forbid",
    "answer":3 }, {
        "question": "Today, ---- people who enjoy winter sports is much greater than that of twenty years ago.",
    "option1": "a number of",
    "option2": "many",
    "option3": "a great deal of",
    "option4": "the number of",
    "answer":4 }, {
        "question": "According to the studies, dolphins, whales and ---- other sea creatures use highly sophisticated navigation systems.",
    "option1": "any",
    "option2": "a little",
    "option3": "many",
    "option4": "much",
    "answer":3 }, {
        "question": " The dietary habits of a child often have ---- to do with that child's eating habits as an adult.",
    "option1": "little",
    "option2": "whole",
    "option3": "every",
    "option4": "a great amount",
    "answer":1 }, {
    "question": "In the United States of America, there are literacy classes for workers, ---- of whom never graduated from high school.",
    "option1": "a little",
    "option2": "much",
    "option3": "any",
    "option4": "many",
    "answer": 4}, {
        "question": "The storm continued for ---- of the days when we were in New Orleans,·but fortunately there wasn't ---- damage in the city.",
    "option1": "a few / many",
    "option2": "several / a lot",
    "option3": "all / a little",
    "option4": "most / much",
    "answer": 4}, {
        "question": "Heavy fines and jail sentences have made ---- difference in preventing elephant poaching for their tusks.",
    "option1": "the number of",
    "option2": "a few",
    "option3": "little",
    "option4": "many",
    "answer":3 }, {
    "question": "Although ---- species of fox are reddish in color, ---- Arctic fox is often pure white.",
    "option1": "a great amount of / an",
    "option2": "any / the",
    "option3": "plenty / the",
    "option4": "most / the",
    "answer": 4}, {
    "question": "Bill Is a man _____ is interesting to talk with, but _____ stories about himself are so incredible that not many people believe them.",
    "option1": "which / that",
    "option2": "who / whose",
    "option3": "that / what",
    "option4": "whom / when",
    "answer":2 }, {
    "question": "You haven't read the new book that has been so highly acclaimed yet,____?",
    "option1": "haven't you",
    "option2": "have you",
    "option3": "hasn't it",
    "option4": "isn't it",
    "answer": 2} , {
    "question": "I can hardly go to any concerts ___ the high price of the tickets.",
    "option1": "on account of",
    "option2": "supposing",
    "option3": "whereas",
    "option4": "in case",
    "answer": 1}, {
    "question": "There are buses___hour, but with the security situation so unsettled, no one is sure___the journey will take.",
    "option1": "every / how long",
    "option2": "all / however",
    "option3": "each / how often",
    "option4": "most / how much",
    "answer": 1}, {
    "question": "The president cannot decide how to deal with the crisis, and_____his advisors.",
    "option1": "so do",
    "option2": "nor are",
    "option3": "neither can",
    "option4": "as can",
    "answer": 3}, {
        "question": "My father gave me two English books ___ he thought I would be able to read, but in fact____was suitable for my level.",
    "option1": "that / some",
    "option2": "who / none",
    "option3": "which / neither",
    "option4": "when / both",
    "answer":3 }, {
    "question": "Both of the job offers are interesting, but the position in Izmir seems to be ____ suitable for me.",
    "option1": "much",
    "option2": "more",
    "option3": "such",
    "option4": "ever",
    "answer":2 }, {
    "question": "The people for _____ I work have gone on holiday, so the office has been quite relaxed this week.",
    "option1": "whom",
    "option2": "who",
    "option3": "what",
    "option4": "that",
    "answer": 1 }];